<a href="https://colab.research.google.com/github/tamantosawar/PYLEARN/blob/main/PYPLEARN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
seq=[1,2,3,4,5]

In [ ]:
for jel in seq:
  print("HEllo ",jel)

HEllo  1
HEllo  2
HEllo  3
HEllo  4
HEllo  5


In [ ]:
i=1
while i<5:
  i=i+1
  print('i is : {}'.format(i))

i is : 2
i is : 3
i is : 4
i is : 5


In [ ]:
for x in seq:
  print(x)

1
2
3
4
5


In [ ]:
range(0,9)

range(0, 9)

In [ ]:
x=list(range(5,9))

In [ ]:
out =[]
for n in x:
  out.append(n**2)

In [ ]:
out

[25, 36, 49, 64]

In [ ]:
List Comprehention

In [ ]:
[num ** 2 for num in x]

[25, 36, 49, 64]

In [ ]:
out=[num**2 for num in x]

In [ ]:
out

[25, 36, 49, 64]

In [ ]:
# function allow to not write same code again and again
def fun(name="DEfault name"):
  print('HEllo '+name)

In [ ]:
def funR(num):
  return num**3

funR(8)

512

In [ ]:
fun()

HEllo DEfault name


In [ ]:
# docutmentation string for multiline comment


In [ ]:
def f():
  """ dfkd
dkfdkfdk
dfjfhdskf
dfdksfsk
 """

In [ ]:
range

range

#map function - built in function  it executes a specified function for each item in an iterable.
map(function , iterables)

In [ ]:
def myfunc(a):
  return a**2

In [ ]:
map(myfunc,(1,2,3),(5,6,7))

In [ ]:
list(map(myfunc,(1,2,3),(5,6,7)))

[6, 8, 10]

In [ ]:
seq=[1,2,3,4,5,6,7,8]

In [ ]:
list(map(myfunc,seq))

[1, 4, 9, 16, 25, 36, 49, 64]

LAmbda Function is a small anonymous function
can have any number of arguments but only one expression



In [ ]:
t=lambda var: var**2

In [ ]:
t(4)

16

In [ ]:
# using lambda in MAP

In [ ]:
list(map(lambda n:n**2,seq))

[1, 4, 9, 16, 25, 36, 49, 64]

**Filter function
filter out element from a sequence**
filter(function or lamda expression ,sequence)
 work on boolean values  

In [ ]:
list(filter(lambda n: n%2==0,seq))

[2, 4, 6, 8]

In [ ]:
s='HEllo My name is Taman'

In [ ]:
s.split('i') # split on particular element

['HEllo My name ', 's Taman']

Dictionary

In [ ]:
d={'k1':1,'k2':2}

In [ ]:
d

{'k1': 1, 'k2': 2}

In [ ]:
d.keys()

dict_keys(['k1', 'k2'])

In [ ]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [ ]:
d.values()

dict_values([1, 2])

**List **

In [ ]:
lst=[1,2,3,4,5]

In [ ]:
lst.pop()

5

In [ ]:
lst

[1, 2, 3, 4]

In [ ]:
lst.extend(seq)

In [ ]:
lst

[1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
lst.append('new')

In [ ]:
lst

[1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 'new']

In [ ]:
lst.pop(1) #passing index

3

In [ ]:
'x' in lst

False

In [ ]:
1 in lst

True

In [ ]:
#tuple unpacking
x=[(1,2),(3,4),(5,6)]

In [ ]:
for item in x:
  print(item)

(1, 2)
(3, 4)
(5, 6)


In [ ]:
for(a,b)in x:
  print(a)
  print(b)

1
2
3
4
5
6


**Numpy  Linear Algebra library for pyhton  & Main Building block for data science libraries **
Numpy is incredibly fast , as it has binding with C libraries
Numpy comes with two flavors :
1.   Vectors : 1d arrays
2.   Matrices: 2d & can have 1 row n 1 clumn too



Numpy Arrays

```
# This is formatted as code
```



In [ ]:
 my_list=[1,2,3]

In [ ]:
import numpy as np

In [ ]:
arr= np.array(my_list)

In [ ]:
mymat=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
mat= np.array(mymat)

In [ ]:
np.arange(0,11,2) # start end steps gives integers

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#creating numerical sequence
np.linspace(0,10,10)# start , end , numer of points requires

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.76316082, 0.44584924])

In [ ]:
np.random.rand(5,5)

array([[0.68644951, 0.95095621, 0.45999523, 0.8644928 , 0.19692695],
       [0.82973456, 0.42579745, 0.81467075, 0.32901661, 0.14577643],
       [0.18323089, 0.0501133 , 0.34629295, 0.64708861, 0.65627267],
       [0.9874344 , 0.12781292, 0.61942275, 0.62012413, 0.83022729],
       [0.70058114, 0.0215483 , 0.02913241, 0.33324718, 0.3382281 ]])

In [ ]:
np.random.randn(2)

array([-2.7662751 ,  1.26480922])

In [ ]:
np.random.randint(1,100,10)

array([20, 77, 29, 67, 10,  7, 57, 93,  4, 73])

In [ ]:
ar=np.arange(25)

In [ ]:
ranar=np.random.randint(0,50,10)

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranar

array([25, 20, 12,  1, 42,  9, 45, 12,  8, 13])

In [ ]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranar.min()

1

In [ ]:
ranar.max()

45

In [ ]:
# agrmax return index of maximum value
ranar.argmax()

6

In [ ]:
ranar.argmin()

3

In [ ]:
ar.shape

(25,)

In [ ]:
ranar.shape # return shape of aray "call without ()

(10,)

In [ ]:
ar=ar.reshape(5,5)

In [ ]:
ar.shape

(5, 5)

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,89)

79

In [ ]:
# Indexing and Selection in Numpy

In [ ]:
ar=np.arange(0,11)

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar[-1]

10

In [ ]:
ar[3:11]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
ar[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# numpy array cAN BROADCAST
ar_slice =ar[0:5]

In [ ]:
ar_slice

array([0, 1, 2, 3, 4])

In [ ]:
ar_slice[:]= 89

In [ ]:
ar_slice

array([89, 89, 89, 89, 89])

In [ ]:
ar
# here changes are reflected in original array
# but we made changes in ar_slice
# Because ar_slice is just slice view of original Array actual address is ar only
# numpy provide reference to original array only


array([89, 89, 89, 89, 89,  5,  6,  7,  8,  9, 10])

In [ ]:
# if user need copy of array then explicitly need to mention
ar_copy =ar.copy()

In [ ]:
ar_copy

array([89, 89, 89, 89, 89,  5,  6,  7,  8,  9, 10])

In [ ]:
# now making changes to ar_copy will not be reflected in array
ar_copy[:]=90

In [ ]:
ar_copy

array([90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90])

Here original ar is same and changes  reflected in ar_copy bcoz explicitly mentioned .copy() function


But  just assigning a slice of array to another variable will pass reference of that slice to var and ---any changes in variable slice will be reflected in original too bcoz of reference

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Indexing in 2d Array / Matrix

In [ ]:
import numpy as np

In [ ]:
arr_2d= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [ ]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr_2d[0]

array([1, 2, 3, 4])

In [ ]:
arr_2d[1][1]

6

In [ ]:
arr_2d[1,1]

6

In [ ]:
arr_2d[:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [1]:
import numpy as np

In [2]:
ar=np.arange(1,11)

In [3]:
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
ar_boolean= ar>3

In [5]:
ar_boolean

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [6]:
ar[ar_boolean] # conditional selection

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
ar[ar>5] #conditional Selection

array([ 6,  7,  8,  9, 10])

In [8]:
arr_2d=np.arange(50).reshape(5,10)

In [10]:
arr_2d[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

Numpy Operations
Array with Array
Array with Scalers
Universal Array Function

In [12]:
arr_2d+ arr_2d

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [13]:
arr_2d - 3

array([[-3, -2, -1,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42, 43, 44, 45, 46]])

In [14]:
arr_2d*arr_2d

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401]])

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

#Scaler Operation
Means broadcast a number to every element in array

In [17]:
ar+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [18]:
ar-20

array([-19, -18, -17, -16, -15, -14, -13, -12, -11, -10])

In [19]:
1/0

ZeroDivisionError: ignored

In [20]:
ar/0
# inf means infinity divided by zero

<ipython-input-20-05262bbed824>:1: RuntimeWarning: divide by zero encountered in divide
  ar/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [21]:
ar/ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
ar**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [25]:
# universal array functions

In [26]:
np.sqrt(ar)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [28]:
np.exp(ar)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [29]:
np.max(ar)

10

In [31]:
np.sin(ar)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [33]:
np.log(ar)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])